; Параметры в духе рекомендаций Битрикс (подкорректируйте под проект)
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000
post_max_size = 64M
upload_max_filesize = 64M
default_socket_timeout = 300

date.timezone = Europe/Moscow

opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 100000
opcache.validate_timestamps = 1

session.save_handler = files
session.gc_maxlifetime = 86400

realpath_cache_size = 4096K
realpath_cache_ttl = 600
